/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-variant": "#343536",
        "outline": "#8f9097",
        "on-primary-fixed": "#0d1c32",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#b9c7e4",
        "surface-container-high": "#2a2a2c",
        "secondary-fixed": "#a5b4fc",
        "surface-tint": "#b9c7e4",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#3c4661",
        "surface": "#131315",
        "on-secondary-fixed": "#1e1b4b",
        "on-background": "#e4e2e4",
        "background": "#131315",
        "surface-bright": "#39393b",
        "surface-dim": "#131315",
        "surface-container": "#1f1f21",
        "on-tertiary-fixed": "#101b33",
        "surface-container-highest": "#343536",
        "on-primary-container": "#74829d",
        "on-tertiary-container": "#77819f",
        "surface-container-lowest": "#0e0e10",
        "inverse-surface": "#e4e2e4",
        "on-primary": "#233148",
        "inverse-primary": "#515f78",
        "tertiary-container": "#0d1830",
        "primary": "#b9c7e4",
        "on-surface-variant": "#c5c6cd",
        "tertiary-fixed-dim": "#bcc6e6",
        "on-surface": "#e4e2e4",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1b1b1d",
        "tertiary-fixed": "#d9e2ff",
        "on-secondary": "#1e1b4b",
        "outline-variant": "#44474d",
        "error-container": "#93000a",
        "secondary-container": "#312e81",
        "primary-container": "#0a192f",
        "on-secondary-fixed-variant": "#4338ca",
        "on-secondary-container": "#c7d2fe",
        "inverse-on-surface": "#303032",
        "on-tertiary": "#263049",
        "tertiary": "#bcc6e6",
        "secondary-fixed-dim": "#818cf8",
        "on-primary-fixed-variant": "#39475f",
        "secondary": "#818cf8",
        "primary-fixed": "#d6e3ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "label-caps": ["Inter"],
        "h3": ["Playfair Display"],
        "body-lg": ["Inter"],
        "h2": ["Playfair Display"],
        "body-md": ["Inter"],
        "interactive": ["Inter"],
        "h1": ["Playfair Display"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
